[features]
resolution = true
skip-lint = false

[programs.localnet]
event_invites = "qVy1Hfus32BxCaPNx14QdG8QtGueV7vKJ37UjNbRS2c"

[programs.devnet]
event_invites = "DNZj9E2Zr3dupWJk9Bt6b9eHYdyi9Msv9VzLpv9WQKy6"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm vitest --reporter verbose"

[toolchain]
anchor_version = "0.31.1"
