AWSTemplateFormatVersion: 2010-09-09
Description: >-
  blinks
Transform:
  - AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  CreateEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/createEvent
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - arm64
      MemorySize: 128
      Timeout: 100
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /api/event/create
            Method: GET
        PostEvent:
          Type: Api
          Properties:
            Path: /api/event/create
            Method: POST
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - '*'
          AllowMethods:
            - GET
            - POST
          AllowHeaders:
            - Content-Type
            - Authorization
            - X-Amz-Date
            - X-Api-Key
            - X-Amz-Security-Token
            - X-Amz-User-Agent
          MaxAge: 86400 # Cache control max age in seconds

  RsvpFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/rsvp
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - arm64
      MemorySize: 128
      Timeout: 100
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /api/event/{eventID}/invite/{inviteID}/rsvp
            Method: GET
        PostEvent:
          Type: Api
          Properties:
            Path: /api/event/{eventID}/invite/{inviteID}/rsvp
            Method: POST
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - '*'
          AllowMethods:
            - GET
            - POST
          AllowHeaders:
            - Content-Type
            - Authorization
            - X-Amz-Date
            - X-Api-Key
            - X-Amz-Security-Token
            - X-Amz-User-Agent
          MaxAge: 86400 # Cache control max age in seconds

  GetActionsJsonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/actions
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - arm64
      MemorySize: 128
      Timeout: 100
      Events:
        GetActionsJson:
          Type: Api
          Properties:
            Path: /actions.json
            Method: GET
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - '*'
          AllowMethods:
            - GET
          AllowHeaders:
            - Content-Type
            - Authorization
            - X-Amz-Date
            - X-Api-Key
            - X-Amz-Security-Token
            - X-Amz-User-Agent
          MaxAge: 86400

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: true

Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON
